# Generated by Django 5.2.15 on 2026-07-01 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_converted', 'Lead Converted'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost'), ('ticket_created', 'Ticket Created'), ('ticket_resolved', 'Ticket Resolved'), ('campaign_sent', 'Campaign Sent'), ('workflow_completed', 'Workflow Completed')], max_length=32)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Optional numeric value, e.g. deal revenue.', max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='analytics_m_event_t_37216d_idx')],
            },
        ),
    ]
