# Generated by Django 5.2.15 on 2026-07-01 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_status_changed', 'Lead Status Changed'), ('deal_stage_changed', 'Deal Stage Changed'), ('ticket_created', 'Ticket Created'), ('ticket_escalated', 'Ticket Escalated'), ('customer_onboarded', 'Customer Onboarded'), ('manual', 'Manual Trigger')], max_length=32)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text="Optional field match rules evaluated against the trigger payload, e.g. {'priority': 'high'} or {'status__in': ['new', 'open']}.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('send_email', 'Send Email'), ('send_sms', 'Send SMS'), ('create_task', 'Create Task'), ('assign_lead', 'Auto-assign Lead'), ('escalate_ticket', 'Escalate Support Ticket'), ('request_approval', 'Request Approval'), ('wait', 'Wait / Delay')], max_length=32)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting on Approval'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('log', models.JSONField(blank=True, default=list, help_text='Ordered list of {step, action_type, status, message, at} entries.')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflow.workflow')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstep')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflow.workflowrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='workflow.workflowstep')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['trigger_type', 'is_active'], name='workflow_wo_trigger_96e111_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'order')},
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['workflow', 'status'], name='workflow_wo_workflo_1580c1_idx'),
        ),
    ]
